### ISSUE TITLE
[1.21-Neo] Server crashes on boot.

### ISSUE THREAD

**Issue by Gbergz** [Leclowndu93150/Modular-Angel-Ring#2]
### Info: 
Can't boot server with this mod installed, causes crashes.

### Versions:
NeoForge: 21.0.65
Modular Angel Ring: 1.0.4

### Crash-report: 
https://gist.githubusercontent.com/Gbergz/1263196d9e3593b9a4f2e85c8d339c86/raw/7ad2faf1d08d8c978d891342539b5d73ed2c3dd4/gistfile1.txt

**Comment by Leclowndu93150** [comment]
i'll look into it

**Comment by Leclowndu93150** [comment]
had to rewrite a lot of the code, will be released later in the day
