### ISSUE TITLE
Lates update for Neoforge 1.21 breaks the Serilum full brightness toggle mod.

### ISSUE THREAD

**Issue by CsillaAria** [Leclowndu93150/Modular-Angel-Ring#3]
This is the latest log from my game: https://bytebin.lucko.me/JD9VR0Fx2d
And the latest debug file: https://bytebin.lucko.me/FPVna25rD3

If you need anything else please let me know.

**Comment by Leclowndu93150** [comment]
I found a fix. I'll just disable the upgrade if you have fullbright installed

**Comment by CsillaAria** [comment]
Thank you!

**Comment by Leclowndu93150** [comment]
i can't get fullbright to load

**Comment by Leclowndu93150** [comment]
i'm prob gonna hate myself for that
