### ISSUE TITLE
[1.21.1 Neofore] Modules not craftable

### ISSUE THREAD

**Issue by Neronya11** [Leclowndu93150/Modular-Angel-Ring#4]
I am playing the modpack ATM10 for reference, and I added the mod to try it out, I can make the blank module without issues, but crafting other modules isn't possible, I even checked the github to see the recipe and saw that I needed to use the smithing table and it didn't even let me put the items in when trying blank module and sugar cane.

Latest version of the mod 1.3.0

**Comment by Leclowndu93150** [comment]
i wonder how bad i messed up

**Comment by Leclowndu93150** [comment]
![image](https://github.com/user-attachments/assets/1a8e5289-cea3-43f0-bc1b-4b4530e31e6b)
i mean i works

**Comment by Leclowndu93150** [comment]
![image](https://github.com/user-attachments/assets/8729ee52-50e7-4768-831b-8d56fd382692)
but this is messed up

**Comment by Leclowndu93150** [comment]
![image](https://github.com/user-attachments/assets/3b26f85d-307d-4f78-ac55-199eb078cbcd)
JEI issue

**Comment by Neronya11** [comment]
![Screenshot 2024-09-03 062049](https://github.com/user-attachments/assets/74c3246d-ac2e-46b8-84ba-9b43a343b623)

Odd, it doesn't let me place it in, I wonder if there is some conflict with another mod from the modpack? Playing in All The Mods 10 which focuses in EMI and has JEI as a side help regardless.

**Comment by Leclowndu93150** [comment]
i'll install the modpack

**Comment by Leclowndu93150** [comment]
![javaw_DVMojnEoB2](https://github.com/user-attachments/assets/1d047623-aa61-419d-add6-beff71161f8a)

install update 1.3.2
