### ISSUE TITLE
Taking fall dmg 

### ISSUE THREAD

**Issue by EmmaRavens** [Leclowndu93150/Modular-Angel-Ring#6]
I'm taking fall dmg and drops aren't collected as long as you aren't close to the ground as well

https://github.com/user-attachments/assets/277ff6d3-5414-437f-9f2f-1e41a950c1e1

Neoforge: 21.1.39
Modular Angel Ring: 1.3.2

**Comment by Leclowndu93150** [comment]
I'm gonna tweak

**Comment by EmmaRavens** [comment]
modpack: TNP Limitless 8 v0.17.0
Yes I can fly just fine

**Comment by EmmaRavens** [comment]
another thing I just figured out, if you take dmg mid flight, flight mode is disabled

**Comment by Leclowndu93150** [comment]
errr

**Comment by Leclowndu93150** [comment]
fixed
