### ISSUE TITLE
[1.21.1] - Curio slots being disabled via this mod.

### ISSUE THREAD

**Issue by ToxinZangoose** [Leclowndu93150/Modular-Angel-Ring#8]
Hello,

I love this mod, but I recently discovered an issue that might be game breaking if used in a modpack.

I equipped the angel ring, but I can't fly with it if other mods use curio slots. This causes the user to not be able to fly or use the curios in question.

For example, I had two Ars Nouveau rings of discount and a belt of levitation that wouldn't work with this mod installed. I believe it has something to do with how this mod handles curio/accessories slots.

Please have a look at this when you are able to.

Thank you for your time!

**Comment by Leclowndu93150** [comment]
oh hi, i'll take a look at the issue

**Comment by Leclowndu93150** [comment]
everything is fine, i never got such an issue reported and i have 30k downloads

![image](https://github.com/user-attachments/assets/a63fedf8-80c4-448a-a9d8-6fb608abef43)

**Comment by ToxinZangoose** [comment]
Interesting, I also tried this with other curio mods like Adorned, Curios API Continued, and Accessories (Using the compatibility layer with Curios). 

I am unsure as to what is causing it still, this is Day 2 of trying to figure out where this issue is coming from. Before we close this, can you levitate with the belt while you have the mod installed?

**Comment by Leclowndu93150** [comment]
i got no clue how the belt works, i'll try

**Comment by ToxinZangoose** [comment]
Try holding shift while jumping, if it works, it will make you float upwards.

**Comment by Leclowndu93150** [comment]
oh okay

**Comment by Leclowndu93150** [comment]
yes it works but only because i shifted when i was in the floor
you can't shift when using an angel ring, for some reason
![2024-11-16_23 28 58](https://github.com/user-attachments/assets/279f5991-afa5-41e4-a2ad-b593c301e764)

**Comment by ToxinZangoose** [comment]
Hmm, I don't want the belt to work while flying, but does the belt still work while the angel ring is equipped?

**Comment by Leclowndu93150** [comment]
yes it does

**Comment by Leclowndu93150** [comment]
send the modpack zip even

**Comment by ToxinZangoose** [comment]
[1.21.1 - Angel Ring Glitch.zip](https://github.com/user-attachments/files/17788152/1.21.1.-.Angel.Ring.Glitch.zip)
Here it is with the mod installed.

**Comment by Leclowndu93150** [comment]
oh no bruh i can't fly

**Comment by ToxinZangoose** [comment]
No worries, I already did the same thing.
The angel ring works by itself, but when all the mods are enabled, it causes this issue.
Thank you for helping me even though I'm sure it is late for you!

**Comment by Leclowndu93150** [comment]
how do you know lol

**Comment by ToxinZangoose** [comment]
I saw your profile, that's all. LOL

**Comment by Leclowndu93150** [comment]
🔫🔫🔫
 gonna look at that tomorow

**Comment by ToxinZangoose** [comment]
Alright, I will close this unless you want to keep it open until it's resolved.

**Comment by Leclowndu93150** [comment]
Lithium
