### ISSUE TITLE
Angel ring equipped to bauble, unable to fly

### ISSUE THREAD

**Issue by Theodurp** [Leclowndu93150/Modular-Angel-Ring#9]
Equipped the normal angel ring, but could not fly at all. Unequipped all other baubles to check, still did not work.
Could this be a neoforge issue?
Installed the speed module to check as well, still no luck.

Version is for neoforge 1.21, 1.5.1
Tested on a server.

**Comment by Leclowndu93150** [comment]
remove lithium
